### ISSUE TITLE
development cycles for individuals

### ISSUE THREAD

**Issue by slwu89** [kerguler/sPop2.jl#5]
It would be nice to implement the examples from the sPop paper in sPop2.jl. Figure 1 was produced by a constant development process (mean=50,sd=10) and a death probability which depended on a counter `devcycle` ( $t_{\pi}$ in the paper, example here: https://f1000research.com/articles/7-1220#e4). It seems like we can't replicate that exactly in sPop.jl yet (other than having multiple `Population` objects to represent that counter. @kerguler do you think we should consider adding `devcycle` to the `MemberKey` object or is there a different way to do this?

**Comment by kerguler** [comment]
I completely agree @slwu89, thanks for the note. I've added the devcycle in the new update (as it was implemented in the original sPop) but to replicate the Figure is not so straightforward. It requires both the development and mortality processes to be age-dependent. Although this is just a few lines of code, it would be nice to introduce a bit more flexibility and have the option to link them both also with accumulative processes. And, why stop there? Why don't we have a flexible list of (unnamed) processes following one another in the order defined by the user? All in the next update, I hope!

**Comment by slwu89** [comment]
Cool! 

Yes, I see now that to replicate Fig 1 in that paper would require at the very least, being able to pass a vector of values for `death` rather than a scalar. It would be nice if the code could adapt to a user wanting something more flexible, but defaulting to the very fast version where `death`, `devmn`, and `devsd` are all scalars if the user doesn't want anything more complicated.

**Comment by kerguler** [comment]
Please check the new version, which successfully reproduces some of the published figures. I had to change the interface quite a bit, but provided some examples to describe the new usage. I am not particularly happy with the trick needed to reproduce Figure 1 in the original sPop. Open to suggestions.

Detailed documentation will follow.

**Comment by slwu89** [comment]
I'm not sure what "trick" you mean, it all looks quite logical to me! If you mean the function overloading to get multiple processes, please see #6, I made some changes to allow for arbitrary numbers of processes with less code. The reproduction of the published figure looks great.

**Comment by kerguler** [comment]
The change for multiple processes is elegant @slwu89, many thanks! The trick I meant is in the last part of demo.ipynb, where a function named _custom_ calculates hazard for each individual (rather than what _pars_ does at the beginning of each step). There is quite a room for improvement there, but for later.

**Comment by slwu89** [comment]
Cool! I think we can close this issue.
